 <?php
   $divarray=Array();
           $file=mb_convert_encoding(file_get_contents($row_intro['companylink']),'utf8',"GBK,utf8,big5");  
           $divcounter=0;
           $filetemp=$file;
  while(($divbegin=stripos($filetemp,'<div'))!==false)
           {   
               $filetemp=substr($filetemp,$divbegin);
               $filetemp=substr($filetemp,stripos($filetemp,'>')+1);  
               $divend=stripos($filetemp,'</div');
               $divnext=stripos($filetemp,'<div');                
               
               if($divend<$divnext)
               {               
                $divarray[$divcounter]=substr($filetemp,0,$divend-1);
                $filetemp=substr($filetemp,$divend);  
                $filetemp=substr($filetemp,stripos($filetemp,'>')+1); 
                $divcounter++; 
                $divcountertemp=$divcounter;
                $divend=stripos($filetemp,'</div');
                $divnext=stripos($filetemp,'<div');
                   while($divend<$divnext)
                   {
                $divcountertemp--;
                $divarray[$divcountertemp].=substr($filetemp,0,$divend-1);
                $filetemp=substr($filetemp,$divend);  
                $filetemp=substr($filetemp,stripos($filetemp,'>')+1);       
                $divend=stripos($filetemp,'</div');
                $divnext=stripos($filetemp,'<div');
                   }                   
               }else
               {
               $divarray[$divcounter]=substr($filetemp,0,$divnext-1);
                $filetemp=substr($filetemp,$divnext);  
                $divcounter++;  
               }                                                   
               }
               
               ?>